myproject/website/urls.py
from django.conf.urls import url
from . import views
from django.http import HttpResponse, HttpRequest
from django.views.i18n import JavaScriptCatalog


app_name = 'website'

urlpatterns = [

    url(r'^$', views.ItemView.as_view(), name='item-view'),
    url(r'items/$', views.ItemView.as_view(), name='item-view'),
    url(r'^items/(?P<pk>[0-9]+)/$', views.ItemDetailView.as_view(), name="itemdetail"),
    url(r'^item/(?P<pk>[0-9]+)/$', views.zarezerwuj_item, name="rezerwujitem"),
    url(r'^accounts/profile/', views.profile, name='profile'),
    url(r'^items/update/(?P<pk>[0-9]+)/$', views.wypozycz, name="wypozycz"),
    url(r'^/items/update/profile/', views.profile, name='profile'),
    url(r'o-nas/$', views.o_nas, name='o-nas'),
    url('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'contact_form', views.contact_form, name='contactform'),
]

myproject/wypozyczajka/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.default.views import RegistrationView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('website.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),


]

admin.site.site_header = "Wypozyczajka.com Strona Administratora"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/companies/models.py
from django.db import models

# Create your models here.

class Stock(models.Model):
    ticker = models.CharField(max_length=10)
    open = models.FloatField()
    close = models.FloatField()
    volume = models.IntegerField()

    def __str__(self):
        return self.ticker

myproject/website/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User #one-to-one technique user
from django.db.models.signals import post_save #one-to-one technique user
from django.dispatch import receiver #one-to-one technique user



class Item(models.Model):
    nazwa = models.CharField(max_length=100)
    cena = models.IntegerField(null=True, blank=True)
    zdjecie = models.FileField()
    wlasciciel = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    czy_wypozyczony = models.BooleanField(default=False)
    data_oddania = models.DateField(null=True, blank=True)
    data_wypozyczenia = models.DateField(null=True, blank=True)
    do_zaplaty = models.IntegerField(null=True, blank=True)
    opis = models.TextField(default="Opis przedmiotu. Jeśli to widzisz, zmodyfikuj opis przedmiotu przez panel administratora.")
    minimalny_okres = models.IntegerField(default="0")
    kaucja = models.IntegerField(null=True, blank=True)
    nowosc = models.BooleanField(default=False)    
    promocja = models.BooleanField(default=False)
    bez_kaucji = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('website:itemdetail', kwargs={'pk': self.pk})

    def update_wlasciciel(self):
        self.wlasciciel = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.nazwa 

myproject/website/forms.py
from django import forms

from django.contrib.admin.widgets import AdminDateWidget

class DatePicker(forms.DateInput):
  input_type = "date"


class RezerwujItemForm(forms.Form):
    data_wypozyczenia = forms.DateField(widget=DatePicker
                                        )
    data_oddania = forms.DateField(widget=DatePicker)


class ContactForm(forms.Form):
    imię = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)
    wiadomość = forms.CharField(
        max_length=2000,
        widget=forms.Textarea(),
        help_text="Wpisz tu swoją wiadomość"
    )
    source = forms.CharField(
        max_length=50,
        widget=forms.HiddenInput()
    )

    def clean(self):
        cleaned_data = super(ContactForm, self).clean()
        imię = cleaned_data.get("imię")
        email = cleaned_data.get("email")
        wiadomość = cleaned_data.get("wiadomość")

        if not imię and not email and not wiadomość:
            raise forms.ValidationError("Musisz coś napisać!")

myproject/companies/views.py
from django.shortcuts import render

myproject/website/views.py
from django.views import generic
from website.models import Item
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
import datetime
from .forms import RezerwujItemForm, ContactForm
from django.views.generic.detail import DetailView


class ItemView(generic.ListView):
    queryset = Item.objects.filter(czy_wypozyczony=False)
    template_name = "website/itemIndex.html"
    context_object_name = "object_list"
    def get_context_data(self, *, object_list=context_object_name, **kwargs):
        context = super().get_context_data(**kwargs)
        context['wypozyczone_list'] = Item.objects.filter(czy_wypozyczony=True)
        return context


class ItemDetailView(DetailView):
    model = Item
    template_name = 'website/itemDetail.html'


def profile(request):
    items = Item.objects.filter(wlasciciel=request.user.id)
    dt = datetime.datetime.utcnow()
    return render(request, 'website/profile.html', {'items': items, 'date': dt})


def wypozycz(request, pk,):
    item = Item.objects.get(id=pk)
    item.wlasciciel = request.user
    item.save()
    return redirect('/accounts/profile/')


def zarezerwuj_item(request, pk):
    item = get_object_or_404(Item, id=pk)
    calendar = datetime
    # Jesli POST request to dane do form
    if request.method == 'POST':

        #Stworz forme i wypelnij informacjami z modelu
        form = RezerwujItemForm(request.POST)

        #Sprawdz czy forma jest poprawna
        if form.is_valid():
            item.data_oddania = form.cleaned_data['data_oddania']
            item.data_wypozyczenia = form.cleaned_data['data_wypozyczenia']
            item.czy_wypozyczony = True
            item.wlasciciel = request.user
            ilosc_dni = item.data_oddania - item.data_wypozyczenia
            item.do_zaplaty = ilosc_dni.days * item.cena
            item.save()

            return redirect('/accounts/profile/')
    # Jesli GET request to
    else:
        proponowana_data_wypozyczenia = datetime.date.today()
        proponowana_data_oddania = datetime.date.today() + datetime.timedelta(days=10)
        form = RezerwujItemForm(initial={'data_oddania': proponowana_data_oddania, 'data_wypozyczenia': proponowana_data_wypozyczenia})

    return render(request, 'website/itemDetailRezerwuj.html', {'form': form, 'item': item})


def o_nas(request):
    return render(request, 'website/oNas.html')


def contact_form(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            pass
    else:
        form = ContactForm()
    return render(request, "website/contact_form.html", {'form': form})

myproject/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}


	
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Wypozyczajka.com</title>
	<link rel="shortcut icon" href='{% static "/media/favicon.ico" %}' type="image/x-icon">
	<link rel="icon" href='{% static "/media/favicon.ico" %}' type="image/x-icon">
    {% block meta %}{% endblock %}
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>


</head>

<body>

<style>

@media (min-width: 1em) {
    .card-columns {
        -webkit-column-count: 1;
        -moz-column-count: 1;
        column-count: 1;
        margin-left: 6em;
        margin-right: 6em;
    }

    #aboutus {
        display: none;
    }

    #logo {
        height: 3em;
        width: 12em;
    }


}


@media (min-width: 34em) {
    .card-columns {
        -webkit-column-count: 2;
        -moz-column-count: 2;
        column-count: 2;
    }

    #aboutus {
        display: block;
    }

    #logo {
        height: 4em;
        width: 16em;
    }
}

@media (min-width: 48em) {
    .card-columns {
        -webkit-column-count: 3;
        -moz-column-count: 3;
        column-count: 3;
    }

    #aboutus {
        display: block;
    }

    #logo {
      height: 4em;
      width: 16em;
    }
}

@media (min-width: 62em) {
    .card-columns {
        -webkit-column-count: 5;
        -moz-column-count: 5;
        column-count: 5;
    }

    #aboutus {
        display: block;
    }

    #logo {
      height: 4em;
      width: 16em;
    }
}

@media (min-width: 75em) {
    .card-columns {
        -webkit-column-count: 6;
        -moz-column-count: 6;
        column-count: 6;
    }

    #aboutus {
        display: block;
    }

    #logo {
      height: 4em;
      width: 16em;
    }

    .card {
      padding-top: 15px;
    }
}
</style>
{% load static %}

<div class="container">


  <!-- TOP BAR NAVIGATION -->
  <nav class="navbar navbar-expand-sm navbar-light bg-faded border border-warning border-top-0 border-left-0 border-right-0 sticky-top" style="background-color: white; color: white;">


    <!-- LOGO -->

        <button class="btn navbar-toggler btn-outline-warning" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <a href="{% url 'website:item-view' %}">
        <img id="logo" src='{% static "/media/logo.png" %}' class="img-fluid" alt="Responsive image">
        </a>

    <!-- BUTTONS -->
    <div class="collapse navbar-collapse" id="nav-content">

          <ul class="navbar-nav ml-auto">

              <li class="nav-item"><a class="nav-link" href="{% url 'website:contactform' %}"><button type="button" class="btn btn-warning" style="margin:0px; min-width: 7em; font-size: 0.8em;">Kontakt</button></a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'website:o-nas' %}"><button type="button" class="btn btn-warning " style="min-width: 7em; font-size: 0.8em;">O nas</button></a></li>

              {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="{% url 'website:profile' %}">
              <button type="button" class="btn btn-warning" style="min-width: 7em; font-size: 0.8em;">{{ user.username }} - Moje konto</button>
              </a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}"><button type="button" class="btn btn-warning" style="min-width: 7em; font-size: 0.8em;">Wyloguj się</button></a></li>
              {% endif %}

              {% if user.is_anonymous %}
              <li class="nav-item"><a class="nav-link" href="{% url 'auth_login' %}"><button type="button" class="btn btn-warning" style="min-width: 7em; font-size: 0.8em;">Zaloguj się</button></a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}"><button type="button" class="btn btn-warning" style="min-width: 7em; font-size: 0.8em;">Zarejestruj się</button></a></li>
              {% endif %}


          </ul>
      </div>

  </nav>
  <!-- /TOP BAR NAVIGATION -->

  <!-- ABOUT US -->
  <img id="aboutus" src='{% static "/media/domki.jpg" %}' class="img-fluid" alt="Responsive image" style="opacity: 0.8;">
  <!-- /ABOUT US -->




    {% if user.is_authenticated %}
        {% block item %}
        {% endblock %}
    {% endif %}

        {% block content %}
        {% endblock %}


        {% block onas %}
        {% endblock %}






<!--Footer-->
<footer class="page-footer blue center-on-small-only" style="background-color: #3f007e; color: white; padding: 1em;">
    <!--Footer Links-->

        <div class="row">

            <!--First column-->
            <div class="col-md-6" style="font-size:10px;">
                <h6 class="title">Narzędzia Zyskowscy - wypożyczalnia</h6>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut eros sed lorem fringilla sagittis. In eu mauris id ante pulvinar ultricies. Maecenas viverra sapien purus, sit amet dictum velit ultrices quis. Phasellus dignissim aliquam porta. Curabitur pellentesque euismod leo, sit amet lacinia erat tristique eu. Aenean in lectus fringilla, commodo quam vitae, semper est. Mauris ornare purus in fermentum lacinia. Sed quis turpis in diam tristique dapibus vel at est. Sed blandit placerat nibh, ut eleifend urna. Etiam imperdiet dui viverra dolor malesuada, non finibus urna porta. Aliquam vel tellus nisl. Fusce gravida finibus fringilla. Nam ac diam ac urna fringilla tristique. Phasellus elementum bibendum ullamcorper.</p>
            </div>
            <!--/.First column-->

            <!--Second column-->
            <div class="col-md-6">
                <h5 class="title">Kontakt</h5>
                <ul class="list-unstyled">
                    <li>tel: 739 292 415</li>
                    <li>Grajewo, Konopnickiej 12c</li>
                    <li>Od poniedziałku do piątku 8:00 - 15:00</li>
                    <li>Zapraszamy!</li>
                </ul>
            </div>
            <!--/.Second column-->
        </div>

    <!--/.Footer Links-->

    <!--Copyright-->
    <div class="footer-copyright">
        <div class="container-fluid" style="font-size: 0.8em;">
            © 2018 Copyright: ZyskowscyNarzedzia

        </div>
    </div>
    <!--/.Copyright-->

</footer>
<!--/.Footer-->


​

</div>

<!-- Popper -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
​
<!-- Latest compiled and minified Bootstrap JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</body>
</html>

myproject/website/templates/website/contact_form.html
{% extends 'base.html' %}
{% block content %}


<div class="row">

 <div class="col-sm-4">
 <div style="padding:2em;">
  <h4>Napisz do nas wiadomość:</h4>
  <form method="post" novalidate>
    {% csrf_token %}
    <table border="1">
     {% include 'website/form_bootstrap.html' with form=form %}
    </table>
    <button type="submit">Submit</button>
  </form>
 </div>
 </div>

 <div class="col-sm-8">
 <div style="padding:2em;">
  <h4>Odwiedź nas osobiście:</h4>
  <div id="map" style="width:100%;height:500px;"></div>
  <h4>Lub zadzwoń: 732 001 743 </h4>
 </div>
 </div>

</div>

<script>
// Initialize and add the map
function initMap() {
  // The location of Uluru
  var uluru = {lat: -25.344, lng: 131.036};
  // The map, centered at Uluru
  var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 4, center: uluru});
  // The marker, positioned at Uluru
  var marker = new google.maps.Marker({position: uluru, map: map});
}
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC97DYJk-0SBk7HByqB3FrdJfcfpILGqj8&callback=initMap"
  type="text/javascript"></script>

{% endblock %}

myproject/website/templates/website/form_bootstrap.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
{% endfor %}

myproject/website/templates/website/itemDetail.html
{% extends 'base.html' %}

{% block content %}

<style>
	/* Dropdown Button */
.dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
}

/* The container <div> - needed to position the dropdown content */
.dropdown {
    position: relative;
    display: inline-block;
}

/* Dropdown Content (Hidden by Default) */
.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

/* Links inside the dropdown */
.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

/* Change color of dropdown links on hover */
.dropdown-content a:hover {background-color: #ddd}

/* Show the dropdown menu on hover */
.dropdown:hover .dropdown-content {
    display: block;
}

/* Change the background color of the dropdown button when the dropdown content is shown */
.dropdown:hover .dropbtn {
    background-color: #3e8e41;
}
</style>

<div class="p-5">



		<div class="card text-center border border-warning">
			<span style="font-weight: bold;">{{ item.nazwa }}</span>
               
			<div class="card-body">
				<img class="img-fluid" src="{{ item.zdjecie.url }}" >
			</div>
                        <div class='text-left'>
                        {{ item.opis }} 
                        </div>
			{% if user.is_authenticated %}
			



				{% else %}
				<a href="{% url 'auth_login' %}" class="btn btn-warning btn-lg active" role="button"
				   aria-pressed="true">Zaloguj się aby zarezerwować</a>
			{% endif %}

			</div>

		</div>



	</div>

{% endblock %}

myproject/website/templates/website/itemDetailRezerwuj.html
{% extends 'base.html' %}
{% block content %}




<div class='container'>
<div class="row text-center">

 <div class='col-lg-2'></div>
	
 <div class='col-lg-8 p-5'>	
		
		<div class="card border border-warning" style="min-width: 200px;">
		
			<span class="p-3" style="font-weight: bold;">{{ item.nazwa }}</span>
		
			<div class="card-body text-center">
				<img class="img-fluid" src="{{ item.zdjecie.url }}" >
			</div>
		
                         <div class="text-left p-3">
                             <h5 class="text-center mt-2">Opis:</h5> 
                            {{ item.opis }}
                         </div>


			{% if user.is_authenticated %}
		
			<form method="POST">
				{% csrf_token %}
				<div class="row">
					<div class="col-1"></div>
					<div class="col-10">
						<h5>Wpisz datę wypożyczenia i datę oddania przedmiotu:</h5>
						{% include 'website/form_bootstrap.html' with form=form %}
						<button type="submit" class="btn btn-primary">Rezerwuj</button>
					</div>
					<div class="col-1"></div>
				</div>
			</form>
		
                        <span style="font-size: 0.7em;">Uwaga, wypożyczone rzeczy należy oddać przed zamknięciem lokalu określonego dnia</span>
		
		        			
				{% else %}
				<a href="{% url 'auth_login' %}" class="btn btn-primary btn-lg active" role="button"
				   aria-pressed="true">Zaloguj się aby zarezerwować
				</a>
			{% endif %}
	  	
		</div>
</div>

 <div class='col-lg-2'></div>	

</div>
</div>


{% endblock %}

myproject/website/templates/website/itemIndex.html
{% extends 'base.html' %}
{% block content %}

<style>

@media (min-width: 1em) {
    .card-columns {
        -webkit-column-count: 1;
        -moz-column-count: 1;
        column-count: 1;
        margin-left: 6em;
        margin-right: 6em;
    }

    #aboutus {
        display: none;
    }

    #logo {
        height: 3em;
        width: 12em;
    }


}


@media (min-width: 34em) {
    .card-columns {
        -webkit-column-count: 2;
        -moz-column-count: 2;
        column-count: 2;
    }

    #aboutus {
        display: block;
    }

    #logo {
        height: 4em;
        width: 16em;
    }
}

@media (min-width: 48em) {
    .card-columns {
        -webkit-column-count: 3;
        -moz-column-count: 3;
        column-count: 3;
    }

    #aboutus {
        display: block;
    }

    #logo {
      height: 4em;
      width: 16em;
    }
}

@media (min-width: 62em) {
    .card-columns {
        -webkit-column-count: 5;
        -moz-column-count: 5;
        column-count: 5;
    }

    #aboutus {
        display: block;
    }

    #logo {
      height: 4em;
      width: 16em;
    }
}

@media (min-width: 75em) {
    .card-columns {
        -webkit-column-count: 6;
        -moz-column-count: 6;
        column-count: 6;
    }

    #aboutus {
        display: block;
    }

    #logo {
      height: 4em;
      width: 16em;
    }

    .card {
      padding-top: 15px;
    }
}
</style>



<blockquote class="blockquote" style="font-size:1.5em; color: #3f007e; border-style: solid; border-width: 8px 0px 0px 0px;">Przedmioty dostępne w punkcie:  </blockquote>
<div class="card-columns mt-2" style="font-size: 0.8em;">
	{% for item in object_list %}
            <div class="card text-center border border-warning">
              <span style="font-weight: bold;">{{ item.nazwa }}</span>
{% if item.nowosc %}<span class="badge badge-danger">Nowość</span>{% endif %}
{% if item.promocja %}<span class="badge badge-success">Promocja</span>{% endif %}
{% if item.bez_kaucji %}<span class="badge badge-primary">Bez Kaucji</span>{% endif %}
              <div class="card-body" style="padding:0px;">
                <a href="{% url 'website:rezerwujitem' item.id %}">
                  <div><img style="height:100px; width:120px;" class="img-fluid"  src="{{ item.zdjecie.url }}"></div>
                </a>
              </div>
              <div style="padding:0px; background-color:white; font-size: 0.96em;">
                <ul class="list-unstyled text-left ml-1">
                 <li>cena: <strong class="text-right">{{ item.cena }}zł/dzień</strong></li>
{% if item.minimalny_okres %}  <li>minimalny okres:<strong class="text-right"> {{ item.minimalny_okres }} dni</strong></li>{% else %}<li><strong class="text-right">wypożyczaj ile chcesz</strong></li> {% endif %}
                 <li>kaucja:{% if item.kaucja %} <strong>{{ item.kaucja }} zł</strong> {% else %}<strong> brak</strong>{% endif %}</li>
                </ul>
              </div>
            </div>
	{% endfor %}
</div>





<blockquote class="blockquote" style="font-size:1.5em; color: #3f007e; border-style: solid; border-width: 8px 0px 0px 0px;">Na te przedmioty musisz zaczekać: </blockquote>
<div class="card-columns mt-2" style="font-size: 0.8em;">
	{% for item in wypozyczone_list %}
           
            <div class="card text-center border border-warning">
              <span style="font-weight: bold;">{{ item.nazwa }}</span>
{% if item.nowosc %}<span class="badge badge-danger">Nowość</span>{% endif %}
{% if item.promocja %}<span class="badge badge-success">Promocja</span>{% endif %}
{% if item.bez_kaucji %}<span class="badge badge-primary">Bez Kaucji</span>{% endif %}
              <div class="card-body" style="padding:0px;">
                <a href="{% url 'website:rezerwujitem' item.id %}">
                  <div><img style="height:100px; width:120px;" class="img-fluid"  src="{{ item.zdjecie.url }}"></div>
                </a>
              </div>
              <div style="padding:0px; background-color:white; font-size: 0.96em;">
                <ul class="list-unstyled">
                 <li><span style="font-weight: bold;">{{ item.cena }}zł</span>/dzień</li>
                 <li>minimalny okres: {{ item.minimalny_okres }} dni</li>
                 <li>wypożyczony do {{ item.data_oddania }}</li>
                </ul>
              </div>
            </div>
	{% endfor %}
</div>

{% endblock %}

myproject/website/templates/website/item_form.html
{% extends 'base.html' %}


{% block item %}



    <div class="row">

		<div class="col-sm-4"></div>

       <div class="col-sm-4">
            <div class="card">


                    <form class="form-group mx-auto" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_bootstrap.html' with form=form %}


                        <div class="form-group">
                            <div class=" col-sm-10">
                                <button type="submit" class="btn btn-success">Dodaj przedmiot</button>
                            </div>
                        </div>

                    </form>


            </div>
        </div>

        <div class="col-sm-4"></div>



    </div>



{% endblock %}

myproject/website/templates/website/item_update_form.html
{% extends 'base.html' %}

{% block item %}

<div class="container">



		<div class="card">

           ty jestes {{user.get_username}}
        <br><br>
           item nalezy do  {{ item.wlasciciel.get_username }}


		</div>

        <a class="btn btn-primary" href="{% url 'website:wypozycz' %}">Wypozycz wypozycz</a>

        <form action="" method="post">{% csrf_token %}
            {{ form }}
            <input type="submit" value="Update" />
        </form>

	</div>

{% endblock %}